id = "verilog"
name = "Verilog"
description = "Verilog and SystemVerilog support"
version = "0.0.1"
schema_version = 1
authors = ["Owen Law <owenlaw222@gmail.com>"]
repository = "https://github.com/someone13574/zed-verilog-extension"

[language_servers.verible-ls]
name = "Verible LS"
languages = ["Verilog", "SystemVerilog"]

[grammars.verilog]
repository = "https://github.com/tree-sitter/tree-sitter-verilog"
commit = "075ebfc84543675f12e79a955f79d717772dcef3"
