id = "verilog"
name = "Verilog"
description = "Verilog and SystemVerilog support"
version = "0.0.8"
schema_version = 1
authors = ["Owen Law <owenlaw222@gmail.com>"]
repository = "https://github.com/someone13574/zed-verilog-extension"

[language_servers.verible]
name = "Verible"
languages = ["Verilog", "SystemVerilog"]

[language_servers.veridian]
name = "Veridian"
languages = ["Verilog", "SystemVerilog"]

[grammars.verilog]
repository = "https://github.com/gmlarumbe/tree-sitter-systemverilog"
commit = "f34d166ab50f6dcd5c546d9ed342cc6b96445f80"
