id = "verilog"
name = "Verilog"
description = "Verilog and SystemVerilog support"
version = "0.0.12"
schema_version = 1
authors = ["someone13574 <owenlaw222@gmail.com>"]
repository = "https://github.com/someone13574/zed-verilog-extension"

[language_servers.verible]
name = "Verible"
languages = ["Verilog", "SystemVerilog"]

[language_servers.veridian]
name = "Veridian"
languages = ["Verilog", "SystemVerilog"]

[language_servers.slang]
name = "Slang"
languages = ["Verilog", "SystemVerilog"]

[grammars.systemverilog]
repository = "https://github.com/gmlarumbe/tree-sitter-systemverilog"
commit = "e88937e66adc3ee7be0bfe40b7e937eafe4212bb"
