id = "verilog"
name = "Verilog"
description = "Verilog and SystemVerilog support"
version = "0.0.6"
schema_version = 1
authors = ["Owen Law <owenlaw222@gmail.com>"]
repository = "https://github.com/someone13574/zed-verilog-extension"

[language_servers.verible]
name = "Verible"
languages = ["Verilog", "SystemVerilog"]

[language_servers.veridian]
name = "Veridian"
languages = ["Verilog", "SystemVerilog"]

[grammars.verilog]
repository = "https://github.com/gmlarumbe/tree-sitter-systemverilog"
commit = "0dacb911daa9614a7c7e79a594d4cb9f478e6554"
